schema_version: 1

context:
  name: cuequivariance-jax
  version: "0.11.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/cuEquivariance/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fd60fbf4d3c2a6208f4a1bbe3b6dc216a18ceff410706e0db665c314cc1a1937

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install ./cuequivariance_jax -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - cuequivariance
    - einops
    - jax
    - packaging

tests:
  - python:
      imports:
        - cuequivariance_jax
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: CUDA accelerated equivariant operations
  license: Apache-2.0
  license_file: LICENSES/LICENSE
  homepage: https://github.com/NVIDIA/cuEquivariance

extra:
  recipe-maintainers:
    - fxcoudert
